### ISSUE TITLE
Precompilation error on Windows

### ISSUE THREAD

**Issue by apraga** [TidierOrg/TidierFiles.jl#37]
Hi,

Importing `TidierFiles` fails to precompile with julia 1.12.

Log
```[ Info: Precompiling TidierFiles [8ae5e7a9-bdd3-4c93-9cc3-9df4d5d947db] (cache misses: wrong dep version loaded (2))
WARNING: Imported binding PrettyTables.compact_type_str was undeclared at import time during import to ReadStatTables.
ERROR: LoadError: invalid method definition in ReadStatTables: exported function PrettyTables.compact_type_str does not exist
Stacktrace:
  [1] top-level scope
    @ C:\Users\apraga\.julia\packages\ReadStatTables\09Kv8\src\LabeledArrays.jl:479
  [2] include(mapexpr::Function, mod::Module, _path::String)
    @ Base .\Base.jl:307
  [3] top-level scope
    @ C:\Users\apraga\.julia\packages\ReadStatTables\09Kv8\src\ReadStatTables.jl:59
  [4] include(mod::Module, _path::String)
    @ Base .\Base.jl:306
  [5] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base .\loading.jl:2997
  [6] top-level scope
    @ stdin:5
  [7] eval(m::Module, e::Any)
    @ Core .\boot.jl:489
  [8] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:2843
  [9] include_string
    @ .\loading.jl:2853 [inlined]
 [10] exec_options(opts::Base.JLOptions)
    @ Base .\client.jl:315
 [11] _start()
    @ Base .\client.jl:550
in expression starting at C:\Users\apraga\.julia\packages\ReadStatTables\09Kv8\src\LabeledArrays.jl:479
in expression starting at C:\Users\apraga\.julia\packages\ReadStatTables\09Kv8\src\ReadStatTables.jl:1
in expression starting at stdin:5
ERROR: LoadError: Failed to precompile ReadStatTables [52522f7a-9570-4e34-8ac6-c005c74d4b84] to "C:\\Users\\apraga\\.julia\\compiled\\v1.12\\ReadStatTables\\jl_AB65.tmp".
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:44
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool; flags::Cmd, cacheflags::Base.CacheFlags, reasons::Dict{String, Int64}, loadable_exts::Nothing)
    @ Base .\loading.jl:3284
  [3] (::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}})()
    @ Base .\loading.jl:2652
  [4] mkpidlock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:93
  [5] #mkpidlock#7
    @ C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:88 [inlined]
  [6] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:114
  [7] #invokelatest_gr#232
    @ .\reflection.jl:1282 [inlined]
  [8] invokelatest_gr
    @ .\reflection.jl:1274 [inlined]
  [9] maybe_cachefile_lock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base .\loading.jl:3855
 [10] maybe_cachefile_lock
    @ .\loading.jl:3852 [inlined]
 [11] __require_prelocked(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:2638
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2465
 [13] macro expansion
    @ .\loading.jl:2393 [inlined]
 [14] macro expansion
    @ .\lock.jl:376 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2358
 [16] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2334
 [17] top-level scope
    @ C:\Users\apraga\.julia\packages\TidierFiles\oZTLm\src\TidierFiles.jl:8
 [18] include(mod::Module, _path::String)
    @ Base .\Base.jl:306
 [19] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base .\loading.jl:2997
 [20] top-level scope
    @ stdin:5
 [21] eval(m::Module, e::Any)
    @ Core .\boot.jl:489
 [22] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:2843
 [23] include_string
    @ .\loading.jl:2853 [inlined]
 [24] exec_options(opts::Base.JLOptions)
    @ Base .\client.jl:315
 [25] _start()
    @ Base .\client.jl:550
in expression starting at C:\Users\apraga\.julia\packages\TidierFiles\oZTLm\src\TidierFiles.jl:1
in expression starting at stdin:5
ERROR: LoadError: Failed to precompile TidierFiles [8ae5e7a9-bdd3-4c93-9cc3-9df4d5d947db] to "C:\\Users\\apraga\\.julia\\compiled\\v1.12\\TidierFiles\\jl_985D.tmp".
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:44
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool; flags::Cmd, cacheflags::Base.CacheFlags, reasons::Dict{String, Int64}, loadable_exts::Nothing)
    @ Base .\loading.jl:3284
  [3] (::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}})()
    @ Base .\loading.jl:2652
  [4] mkpidlock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}}, at::String, pid::Int32; kwopts::@Kwargs{stale_age::Int64, wait::Bool})
    @ FileWatching.Pidfile C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:93
  [5] #mkpidlock#7
    @ C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:88 [inlined]
  [6] trymkpidlock(::Function, ::Vararg{Any}; kwargs::@Kwargs{stale_age::Int64})
    @ FileWatching.Pidfile C:\Users\apraga\scoop\apps\julia\current\share\julia\stdlib\v1.12\FileWatching\src\pidfile.jl:114
  [7] #invokelatest_gr#232
    @ .\reflection.jl:1282 [inlined]
  [8] invokelatest_gr
    @ .\reflection.jl:1274 [inlined]
  [9] maybe_cachefile_lock(f::Base.var"#__require_prelocked##0#__require_prelocked##1"{Base.PkgId, String, Dict{String, Int64}}, pkg::Base.PkgId, srcpath::String; stale_age::Int64)
    @ Base .\loading.jl:3855
 [10] maybe_cachefile_lock
    @ .\loading.jl:3852 [inlined]
 [11] __require_prelocked(pkg::Base.PkgId, env::String)
    @ Base .\loading.jl:2638
 [12] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base .\loading.jl:2465
 [13] macro expansion
    @ .\loading.jl:2393 [inlined]
 [14] macro expansion
    @ .\lock.jl:376 [inlined]
 [15] __require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2358
 [16] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:2334
 [17] include(mapexpr::Function, mod::Module, _path::String)
    @ Base .\Base.jl:307
 [18] top-level scope
    @ REPL[1]:1
in expression starting at C:\Users\apraga\code\plot\vaf-multiplot.jl:2```

Pkg.status()

```
julia> Pkg.status()
Status `C:\Users\apraga\code\mosaique\plot\Project.toml`
  [cbdf2221] AlgebraOfGraphics v0.11.8
  [336ed68f] CSV v0.10.15
  [13f3f980] CairoMakie v0.15.6
  [324d7699] CategoricalArrays v1.0.1
  [a93c6f00] DataFrames v1.8.0
  [1313f7d8] DataFramesMeta v0.15.4
  [e9467ef8] GLMakie v0.13.6
  [2913bbd2] StatsBase v0.34.6
```

Thanks !

**Comment by apraga** [comment]
Cannot reproduce on another Windows.

**Comment by apraga** [comment]
Cleaning the julia cache solves the issue !
